### ISSUE TITLE
add a link to trust on the deposit page

### ISSUE THREAD

**Issue by jedmccaleb** [stellarchat/desktop-client#105]
Right here you should let the user trust the anchor so they don't have to navigate to some other tab and then come back:
![no link](https://user-images.githubusercontent.com/399067/29735264-89875016-89ac-11e7-88b6-41f845b3386c.png)

**Comment by RickyND** [comment]
Hey Jed,
As soon as I choose a trust line, this comes up:
{"type":"https://stellar.org/horizon-errors/not_found","title":"Resource Missing","status":404,"detail":"The resource at the url requested was not found. This is usually occurs for one of two reasons: The url requested is not valid, or no data in our database could be found with the parameters provided.","instance":"horizon-live-001/LigQMDpFPB-111183096"}
Same for other trust lines.
