### ISSUE TITLE
Transactions show an unknown transaction

### ISSUE THREAD

**Issue by LeaTex** [stellarchat/desktop-client#109]
My public key is:
GD3EETINIIH4TXCB4S3CKI2UW6GIVOKIAWYO4TDMUNASOVRGBCSK6QR2

The transactions history shows me one that I don't know. Is it possible?

See attachment. Second transaction (offer BTC/XLM) is not mine.

![lumens_trx](https://user-images.githubusercontent.com/6115573/31637364-c20d944c-b2a4-11e7-8c2c-df918f65eda6.png)

**Comment by stellarchat** [comment]
The history part need to fix.

**Comment by stellarchat** [comment]
this will be fixed in v3.6
