### ISSUE TITLE
Show all decimals in Balance view

### ISSUE THREAD

**Issue by LeaTex** [stellarchat/desktop-client#110]
In Balance view it's not consistent with reality.

Example:
- Estimated value of holdings: 81 XLM
- Balance: 40.000 XLM + 0.000 BTC

![btc_balance](https://user-images.githubusercontent.com/6115573/31637890-314dcf46-b2a7-11e7-823a-b884fe10f520.png)

It must show me the real balance as I can see in Trade view:
You have 0.0003291 BTC
You have 39.99998 XLM

![trade_balance](https://user-images.githubusercontent.com/6115573/31637894-35fa2102-b2a7-11e7-83fc-fabda0aa2585.png)

**Comment by stellarchat** [comment]
BTC should be a special case.
