### ISSUE TITLE
404

### ISSUE THREAD

**Issue by mauriceip** [stellarchat/desktop-client#112]
{"type":"https://stellar.org/horizon-errors/not_found","title":"Resource Missing","status":404,"detail":"The resource at the url requested was not found. This is usually occurs for one of two reasons: The url requested is not valid, or no data in our database could be found with the parameters provided.","instance":"horizon-live-003/0TWnZXMGoc-32038039"}

**Comment by stellarchat** [comment]
It should be the account is not funded yet. Need to make the error message more user friendly
