### ISSUE TITLE
Transaction shows sent in Wallet but never received into Bittrex  account

### ISSUE THREAD

**Issue by mtdaly88** [stellarchat/desktop-client#123]
Hello, 

I sent a transaction to Bittrex, but I did not receive my Lumens. In the Stellar wallet, it shows sent, but I do not have a deposit or even a pending deposit in my Bittrex account. Any way we can check the blockchain to see what happened? 

Account: GCOX5MJ3BL6TUHVHVLHUDXABES3UYOGHDJRNYJ7UP3TRKCDVNAY6AFYE

**Comment by jedmccaleb** [comment]
you can check in steexp.com Likely you didn't include a memo. You have to contact bittrex

Ran Liang you guys should maybe block sending to exchanges when people don't include a memo. stellarterm does this.

**Comment by stellarchat** [comment]
It make sense to block the payment to exchanges without memo. this should be added to next version.
