### ISSUE TITLE
https://stellar.org/horizon-errors/not_found

### ISSUE THREAD

**Issue by imkane** [stellarchat/desktop-client#132]
`{"type":"https://stellar.org/horizon-errors/not_found","title":"Resource Missing","status":404,"detail":"The resource at the url requested was not found. This is usually occurs for one of two reasons: The url requested is not valid, or no data in our database could be found with the parameters provided."`

I'm getting this error on the Windows 64-bit client on various screens (History, Inflation Destination, etc)

Any ideas?

**Comment by stellarchat** [comment]
Your account is not activated yet. Ask someone send you some XLM.

**Comment by imkane** [comment]
Why would you close this? It's clearly a bug. Other people are going to ask the same question ;)
