### ISSUE TITLE
StellarWallet executable not in OSX release 

### ISSUE THREAD

**Issue by guezandy** [stellarchat/desktop-client#143]
The entire file structure for the OSX download is:

StellarDesktopOsx64-v3.1.zip
root
- nwjs
- credits.html
- nwjs-v0.20.2-osx-x64
  - nwjs
  - credits.html

I don't see the StellarWallet executable in the folder.

**Comment by pascalandy** [comment]
Trying to make this wallet on my mac as well. Very confusing.
But app do not open.
running 10.11.6

Thanks you

![screen shot 2017-12-21 at 10 03 33 pm](https://user-images.githubusercontent.com/6694151/34283634-de99d36c-e69a-11e7-8d4a-83c257725138.jpg)
![screen shot 2017-12-21 at 10 03 26 pm](https://user-images.githubusercontent.com/6694151/34283635-dea8fd88-e69a-11e7-82ad-dfb0406ca279.jpg)

**Comment by davidvasquez-epitomyze** [comment]
Under Finder > Preferences, in the Advanced tab, enable the "Show all filename extensions" option. This option will show the ".app" extension for the "nwjs.app" file inside of the release ZIP archive.

**Comment by pascalandy** [comment]
I see nwjs.app and it's not launching.

**Comment by davidvasquez-epitomyze** [comment]
Are you running the latest macOS, High Sierra Version 10.13.2?

I also have Node.js installed (for web dev), which is listed as a requirement for building SDC directly from source. Perhaps Node.js is also a dependency for running the executable?

**Comment by liangran** [comment]
I cannot reproduce it on macOS 10.13.2
