### ISSUE TITLE
Sending lumins, getting paymentUnderfunded

### ISSUE THREAD

**Issue by sgehrman** [stellarchat/desktop-client#147]
I assume this is because of a minimum balance issue, but I was leaving 39 lumins in the wallet. So, I thought 20 was the minimum? Should I merge accounts instead? I want to close out this wallet.

**Comment by stellarchat** [comment]
You may have too many XLM forzen. You can remove all the offers and trust lines. Then use the delete account feature since v3.3. Then you can get all the lumens.

**Comment by derekeglindsey** [comment]
I am getting this same error. I open the wallet with 2 XLM and I was testing the withdrawal option by sending 1 XLM back to myself. What is the minimum I must keep in the wallet and the minimum I can send???
