### ISSUE TITLE
Can't send Lumens

### ISSUE THREAD

**Issue by sussidio** [stellarchat/desktop-client#149]
Hi,

I'm trying to send Lumen funds from one XLM address to another and keep getting the attached error.
Can you please help?

Cheers,

Ben
![stellarwallet_2017-12-04_10-07-08](https://user-images.githubusercontent.com/4159559/33531005-872bf74e-d8db-11e7-88fc-2b4271051214.png)

**Comment by coolmatt69** [comment]
Hello, I am also seeing something similar but not the exact same thing. 
![capture](https://user-images.githubusercontent.com/34258136/33586767-001bce24-d939-11e7-9c6e-665bb9283ba3.JPG)

**Comment by stellarchat** [comment]
You can not send all your lumen, every account will froze about 20 XLM. you can send 503 if you have 523. Check your balance menu to see the frozen Lumens.
