### ISSUE TITLE
Not receiving XLM?

### ISSUE THREAD

**Issue by PaulyWalnuts** [stellarchat/desktop-client#150]
I used Changejelly to send my ethereum from coinbase to my stellarwallet address. 
It has gone through in Coinbase but is NOT showing up in my Stellar wallet.
I just opened the wallet and didn't have a 'trust line' or 'anchor' set up. This was my first transaction.

**Comment by visitor56** [comment]
I also used Coinbase to send to Changelly and nothing is going through. I get the error: {"type":"https://stellar.org/horizon-errors/not_found","title":"Resource Missing","status":404,"detail"
I don't find any thing in Settings to be sure the program is online or any information (Help) that would indicate anything was set-up wrong. 
Anyone else have this and know how to fix?

**Comment by Imnaiyasan** [comment]
I'm having this same issue. Anyone figure it out??

**Comment by visitor56** [comment]
I contacted Changelly support from their homepage (at the bottom) and also sent a message on their FB page (ChangellyTeam). They emailed me and took care of it. They were very helpful and I've had no issues since.
visitor56

**Comment by stellarchat** [comment]
Not relate our client. You may contact the one who send the XLM.
