### ISSUE TITLE
XLM help

### ISSUE THREAD

**Issue by lumenboy** [stellarchat/desktop-client#154]
Used Changelly to switch ethereum to xlm, can see transaction was sent but my xlm has not showed up in desktop client, please help.

**Comment by Imnaiyasan** [comment]
Same issue.

**Comment by lumenboy** [comment]
Still waiting and it has been 3 days. Is all my money gone?

**Comment by lumenboy** [comment]
Does anyone know a way to contact Stellar Wallet people for support?

**Comment by overcat** [comment]
Please check your account infomation at [stellarchain.io](https://stellarchain.io), if Changelly send xlm to you, you can find the payment on the website. If you can not find it, please contact Changelly for support.

**Comment by stellarchat** [comment]
overcat is right. contact the one who send you XLM
