### ISSUE TITLE
Reset Base and Counter Asset

### ISSUE THREAD

**Issue by fotoguytim** [stellarchat/desktop-client#155]
I accidentally made my Base and Counter asset XLM.  How do I change the counter to CNY?
![stellar-github](https://user-images.githubusercontent.com/34721240/34224019-6144548e-e58f-11e7-9fb9-af7c17bd8177.PNG)
Thanks in advance!
FotoGuyTim

**Comment by stellarchat** [comment]
You need to add the trust line first. Then it would allow you to choose the base and counter.
