### ISSUE TITLE
History page: Error 404 

### ISSUE THREAD

**Issue by oliever** [stellarchat/desktop-client#156]
I'm getting this error on the history page
![stellar error](https://user-images.githubusercontent.com/43648/34239992-19d7c95c-e646-11e7-88ac-12d3403aaf2e.jpg)

**Comment by kfiresmith** [comment]
+1  - There is a lot of unacceptably ugly traceback-style output that would prevent me from recommending this tool to a casual user.  Please improve error handling and make these exceptions be caught and prettied up before displaying to user.
