### ISSUE TITLE
OS X wallet does not run

### ISSUE THREAD

**Issue by pascalandy** [stellarchat/desktop-client#157]
Trying to make this wallet on my mac as well. Very confusing.
Both apps do not run.
My OSX is: 10.11.6

Thank you!

![screen shot 2017-12-21 at 10 03 33 pm](https://user-images.githubusercontent.com/6694151/34283634-de99d36c-e69a-11e7-8d4a-83c257725138.jpg)
![screen shot 2017-12-21 at 10 03 26 pm](https://user-images.githubusercontent.com/6694151/34283635-dea8fd88-e69a-11e7-82ad-dfb0406ca279.jpg)

**Comment by agordeev** [comment]
I'm haveing the same issue

**Comment by geocontinuum** [comment]
Worked Just fine for me? What is the issue it is a beautiful anonymous setup that provides a wallet and methods to trade into other coins?

**Comment by pascalandy** [comment]
10.11.6 is not supported.
