### ISSUE TITLE
stellar wallet lummens sudenly dissapeared

### ISSUE THREAD

**Issue by Jasvantkhargi** [stellarchat/desktop-client#158]
Dear,

I have been using the latest stellar wallet for a few days and transfer lummens to this desktop wallet.

Today I open my desktop wallet and noticed that lumens are gone.  I had around 3089 lumens  which I downloaded from https://github.com/stellarchat/desktop-client/releases

I have followed the step on how to buy stellar via the below website. https://buystellarlumens.info/

Mystellar address
GDTNY37EZAMQPJIFI5EJOB43LHBVJR4JFKEQDBH7F4ZTGHBFSWMWCS5A
Could you please check what happened to my coins?

**Comment by xeldarith** [comment]
Your address does have 3,087.899 Lumens. S
https://stellarchain.io/address/GDTNY37EZAMQPJIFI5EJOB43LHBVJR4JFKEQDBH7F4ZTGHBFSWMWCS5A

So the problem might be with your desktop/environment(?)

**Comment by stellarchat** [comment]
It could be the node the client connected was out of synchronized. You could try to switch the node in settings.
