### ISSUE TITLE
txInsufficientBalance

### ISSUE THREAD

**Issue by Butker** [stellarchat/desktop-client#160]
Sold 300 stellar, currently having 433 CNY.

When trying to buy or convert into stellar again, i get message txInsufficientBalance, even if i try to buy just 1. Sometimes i also get txBadSeq.

**Comment by stellarchat** [comment]
1, Stellar require you have enough XLM as the network fee. If you do not have enough XLM, it would say txInsufficientBalance. Check your balance first.
2. txBadSeq, just retry later
