### ISSUE TITLE
All my lumens disapparead from my wallet and were randomly sent to an address i'm not familar with

### ISSUE THREAD

**Issue by adod10** [stellarchat/desktop-client#162]
Hello,

This morning i opened my account to find 60,100 of my lumens randomly sent as a payment to this account id: GAV4AKS5YEIYBF62WJUHUIZE5UNKRB3O77G4NUA5NESQ2GPNDD5JRSUH. 

I did not actively send this tranaction nor am i familar with this account ID. 

my account id is: GB6YPGW5JFMMP2QB2USQ33EUWTXVL4ZT5ITUNCY3YKVWOJPP57CANOF3

can you please help as this is quite a bit of my coin. 

<img width="718" alt="screen shot 2017-12-29 at 11 25 36 am" src="https://user-images.githubusercontent.com/34943840/34441681-47e4770a-ec8b-11e7-9712-724775ea7aa0.png">

**Comment by stellarchat** [comment]
A sad story. You may have your secret key leaked. So the one who know your secret key stole your lumens. After I check https://stellarchain.io/address/GAV4AKS5YEIYBF62WJUHUIZE5UNKRB3O77G4NUA5NESQ2GPNDD5JRSUH, I found all your lumens go to GC4KAS6W2YCGJGLP633A6F6AKTCV4WSLMTMIQRSEQE5QRRVKSX7THV6S with memo 875468. It could be a exchange address. You may contact the exchange to check who use these lumens.
