### ISSUE TITLE
"asset sent successfully" but not deducted from balance

### ISSUE THREAD

**Issue by deejaxx** [stellarchat/desktop-client#166]
hi gang. trying to trade out some xlm to btc and send it to anchor{NaoBtc). It trades out okay and sends off,as far as I can tell(it says'asset successfully sent")...but my xlm balance doesnt drop at all. Tried it a number of times with the same result. Ive done this in the past a number of times with no problems.......til now. Help,please!

**Comment by stellarchat** [comment]
It should be the node the wallet connected is not normal. You can try use the https://horizon.stellar.org
