### ISSUE TITLE
Errors on History Tab

### ISSUE THREAD

**Issue by vnaranjo1234** [stellarchat/desktop-client#170]
I am getting the following in the History Tab:
{"type":"https://stellar.org/horizon-errors/not_found","title":"Resource Missing","status":404,"detail":"The resource at the url requested was not found. This is usually occurs for one of two reasons: The url requested is not valid, or no data in our database could be found with the parameters provided.","instance":"horizon-live-002/coycPd7mOQ-169579416"}

 I just created a new wallet and trying to send 30 XLM to my wallet from Binance. Binance is taking some time to send it. I hope that the wallet address that was created for me was a valid one.

**Comment by igotfits1** [comment]
are u still having the same issue? i have the same thing.

**Comment by vnaranjo1234** [comment]
No. My wallet was not activated therefore i was getting those issues. Binance was taking a really long time to transfer my lumens to my wallet. Took about an hour. When they got to the wallet, those errors went away.

**Comment by igotfits1** [comment]
o weird, ok cool.
what's the minimum to get the wallet activated? kinda scared to move over alot an it doesnt work.

**Comment by vnaranjo1234** [comment]
It takes 20. so send about 21 lumens because of the fees.

**Comment by Aynss** [comment]
I am having the same issue. I funded my Stellar Desktop wallet via Binance xlm withdrawal. My Binance transaction history shows that it has been completed but upon checking my wallet, I still have 0 balance and I continue to get the same error message.

**Comment by vnaranjo1234** [comment]
@Aynss Did you receive your funds from binance. It usually takes about 30 minutes for binance to send coins to your wallet depending on network congestion. Once you receive the coins in your stellar wallet, the errors should go away.

**Comment by stellarchat** [comment]
The UI will be improved. Anyway, the account should be funded before you see the balance.
