### ISSUE TITLE
Lost in Transfer funds

### ISSUE THREAD

**Issue by eduardosar** [stellarchat/desktop-client#171]
On: 210 XLM
2017-12-30 20:25:02

ive sent these funds to my wallt and they still have not arrived to destiny, i need help from you guys to see if we can complete this operation: 65996141052829697payment

Destination adress:
GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A | -210 XLM | 

Thank you..

**Comment by stellarchat** [comment]
The binance exchange require a memo in the transaction. You can connect the binance. The wallet will prevent user send to GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A since v3.4
