### ISSUE TITLE
Lumens Sent to NAOBTC address when trying to send to BTC Wallet

### ISSUE THREAD

**Issue by tmill1987** [stellarchat/desktop-client#174]
In July, I attempted to send 78,943 XLM to the BTC Wallet. I did not convert them first, they left my Stellar Wallet desktop client, and we sent to the address:

GBTCBCWLE6YVTR5Y5RRZC36Z37OH22G773HECWEIZTZJSN4WTG3CSOES

My Address is : GBAEDUTCW6NFLXAEXAGDBYV7LDHVMNOEB6QUOOJ6WX3RG3VGFNLSHLW3

Attached is the transaction as shown at stellarChain.io. I have been reaching out to numerous wallets for months now trying to find the 78k+ XLM, I have finally found them within the Stellar Ledger....What can I do to recover these? I now know that this in an address controlled by NAOBTC.  There are a couple of transactions in the activity associated with the GBTC address that seem to mimic mine, a large amount of XLM is sent to this address, but then it is sent back to the user that issued the payment, I am assuming by mistake, just like me. PLEASE HELP!  Stellarchain.io screenshots are attached.

![screenshot 5](https://user-images.githubusercontent.com/35117854/34587351-fd6a3526-f175-11e7-9efe-b935fc3e02af.png)
![screenshot 6](https://user-images.githubusercontent.com/35117854/34587352-fd833c88-f175-11e7-8af9-b8cadbeb7c3e.png)

**Comment by stellarchat** [comment]
resolved after I contact eno
