### ISSUE TITLE
3 confirmations needed (over 2 days)

### ISSUE THREAD

**Issue by pbalzano8** [stellarchat/desktop-client#175]
I exchanged lumens for btc using my naobtc trust over 2 days ago and I still haven't got my btc. When I check my btc under "Deposit" it still says, "3 confirmations needed. this is long term availabe address." How long is a typical confirmation?

**Comment by manran** [comment]
Hi @pbalzano8 
You might check the balance page if you traded your lumens for BTC.naobtc.
the deposit part is how real BTC turns into BTC asset which issued by Naobtc.
