### ISSUE TITLE
Looks like I got robbed!

### ISSUE THREAD

**Issue by DonTeo32** [stellarchat/desktop-client#177]
Just signed into my desktop Stellar Lumens wallet and found this transaction.
![screen shot 2018-01-06 at 21 41 43](https://user-images.githubusercontent.com/35177815/34643791-e83734ae-f32a-11e7-93e7-db7b6ad75a3f.png)
 This is not a transaction that I made and was I wondering if this happened to anyone else.
I never gave out my keys or used my wallet yet.
I just made the initial 43 lumens  deposit to activate it and then some test transactions.
I'm pretty bummed as it's close to 200 dollars with the recent impulse.
My Public Address: GBM4AU73W5EMN2DIQOOW2IO5I3VXEQY6IQPILYVR3LZMQJ3Z4ONVFO5O

Is there any way to stop this or some kind of disciplinary action to the owner of that address?
Thanks beforehand with any help in this matter.
Cheers,
Matt

**Comment by corneyl** [comment]
Did you check if this actually influenced your balance? I have the same in my wallet, but the send transactions shown did not influence my balance. I have the idea that this is a bug in processing batch transactions.

Although, if I quickly calculate your balance, it seems to be right. This tx happened.

**Comment by DonTeo32** [comment]
Hi,
Thanks for the reassurance and your help,  I'll try to check it today.
Cheers,
Matt

**Comment by DonTeo32** [comment]
Now my account is saying 0 Lumens and has been merged with another account 
![screen shot 2018-01-18 at 14 01 24](https://user-images.githubusercontent.com/35177815/35099391-21598364-fc58-11e7-85cd-45d689c4029e.png)
I know it says don`t get to attached to lumens in these wallets.
How do I check my lumen amounts other than in my wallet?
Thanks for your help.
Cheers,
Matt

**Comment by corneyl** [comment]
You can also check your balance by entering your account id at a explorer, e.g.: https://stellar.expert/explorer/account/GBM4AU73W5EMN2DIQOOW2IO5I3VXEQY6IQPILYVR3LZMQJ3Z4ONVFO5O

Maybe some hacker got your private key and used that to steal your XLM. This doesn't mean that this wallet is insecure btw, but maybe it's better to use another one.

**Comment by DonTeo32** [comment]
Well I guess that could be possible but not sure how.
I thought it was all the testing and changing of the minimums.
Looking at where the money went it seems the lumens ended up in
bitcoinindonesia which is a huge exchange in India.
All in all that sucks but thanks for your help.
Cheers
