### ISSUE TITLE
Thoughts on updating to Angular 5

### ISSUE THREAD

**Issue by rgtj2** [stellarchat/desktop-client#179]
Hi!

I'd be willing to help / lead the implementation of an issue I see..

We should update this to use Angular 5.

Being able to use the CLI would be a small win that'd have developer productivity gains, but regardless I think updating to a more modularized structure, using components, unit tests, a type system, the component router, and powerful DI system would be great to have here.

Of course there is similar work that can be done to the 1.x version of the app, and some of those changes could be a stepping stone towards moving to Angular 5. There are a few options for how we'd want to update it anyway (ie just suck it up and update the thing as is, or create a v2 using Angular 5, eject the app from the CLI (or just add it as a dependency w/npm), and use the UpgradeAdapter to downgrade the angular 5 components and use them within the AngularJS app.

I can probably do a spike soon and just look into what the best upgrade path might be..

Thoughts?

**Comment by RiaanWest** [comment]
Hi there

I'm brand new to this project, think you guys are doing an amazing job, and would like to offer any help where I can 😄 

I've been working with Angular 4/5 on projects for the past while, so I could contribute some of the knowledge/experience that I've gained.

So, I'm putting up my hand - let me know how/when you'd like to get cracking ✋

**Comment by RiaanWest** [comment]
@rgtj2 Would you be keen for me to give a hand with this potential refactor?

**Comment by rgtj2** [comment]
@RiaanWest Hey! Sorry for the late reply!

.. I'm slightly hesitant to dive in, for lack of better words, as - aside from a few issues - this wallet has been pretty solid, at least for me..

And wallets seem to be a common project across the board, so I'm not worried about the progress of that category of development for stellar..

I'm also not sure what the state of the project is in terms of how active / collaborative it is.
I have a bunch of other project ideas brewing, too, so this would def have take a back-burner position at best for now.

.. If you're looking for some Angular stuff re:Stellar.. I just started putting this admin dashboard together for fun, as a kind of build-tool / helper / quickstart for interacting with a Horizon server (in this case on a Docker container locally running in 'ephemeral' mode)... https://github.com/rgtj2/stellar-admin-dashboard

**Comment by RiaanWest** [comment]
Hey @rgtj2 - thanks for the reply.

Gotcha - makes sense looking at the low frequency of merges currently. I'll pop over to the other project you mentioned. Maybe I can help out a bit there?

**Comment by stellarchat** [comment]
We do not have plan to upgrade to angular 5. The top priority for us is to complete the stellar features.

**Comment by RiaanWest** [comment]
@stellarchat Are you guys needing an extra brain with some features?

**Comment by stellarchat** [comment]
That is great. For example, we need someone to improve the history of transactions, to show the batch of operations.

**Comment by RiaanWest** [comment]
Sounds good - happy to take a look. What sort of improvements are you thinking of?

**Comment by stellarchat** [comment]
Maybe you can improve the layout of the history menu (include the 3 submenus). The latest code already show the batch of operations.
