### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by igotfits1** [stellarchat/desktop-client#180]
Getting this under the History tab... payments, effects, transactions.

"type":"https://stellar.org/horizon-errors/not_found","title":"Resource Missing","status":404,"detail":"The resource at the url requested was not found. This is usually occurs for one of two reasons: The url requested is not valid, or no data in our database could be found with the parameters provided."

**Comment by Aynss** [comment]
I am having the same issue and I just funded my wallet through Binance. But the XLM is not showing up. :(

**Comment by stellarchat** [comment]
The UI will be updated.
