### ISSUE TITLE
Wallet doesn't exist? Lost 1000 Lumens

### ISSUE THREAD

**Issue by squidm8** [stellarchat/desktop-client#181]
I have sent 1000 XLM to this wallet on an external exchange, and they have not arrived. When I used the wallet address I was given by the client on the Stellar laboratory it doesn't say it exists...

https://horizon-testnet.stellar.org/accounts/GDQGVTX5BBQEXAFZZNP767QFSU4B27O3SORSVLHXYIBKFHEN7UJINE4M

What a joke

**Comment by corneyl** [comment]
I think you send it to a different address, btw, the link you provide is for the testnet. Look here for the pubnet account info: https://horizon.stellar.org/accounts/GDQGVTX5BBQEXAFZZNP767QFSU4B27O3SORSVLHXYIBKFHEN7UJINE4M

**Comment by kfiresmith** [comment]
@squidm8  - you need to provide more information.  As @corneyl mentioned, what little information you did provide is incorrect.  But don't fret, the ledger system will show you where your lumens went.  You just need to provide a reasonable starting point such as the last wallet public address you had the lumens in.  Sounds like that was an exchange wallet, so your best bet there is to provide a transaction ID from within the exchange withdrawal page.  Then you can look up where the lumens went on https://stellarchain.io
