### ISSUE TITLE
Add lumenaut 0% fees inflation pool to wallet UI

### ISSUE THREAD

**Issue by citizen2077** [stellarchat/desktop-client#184]
A new community driven inflation pool has been created which has 0% fees associated. I think it should be added to the options in the UI.

Information here: https://www.reddit.com/r/Stellar/comments/7qsgmp/community_pool_is_live/

**Comment by kfiresmith** [comment]
Is this project abandoned?   There's even a PR submitted for this feature and all it needs is to be merged.  I am starting to think that @stellarchat has decided to work on other things.

**Comment by Stukongeluk** [comment]
@kfiresmith It is added since a few minutes ago, so this issue should be closed ;)

**Comment by kfiresmith** [comment]
Great to see @stukongeluk!
