### ISSUE TITLE
Update minimum required balance to 1 lumen

### ISSUE THREAD

**Issue by zhuayun** [stellarchat/desktop-client#185]
"Starting at 10 AM PT on January 11, 2018, the base reserve will be reduced 20-fold from 10 lumens to 0.5 lumens."

See https://www.lumenauts.com/blog/stellar-account-minimum-balance-to-reduce-by-20x

**Comment by imsys** [comment]
I thought the minimum was already reduced, but it was not.

You can check it here:

https://github.com/stellar/stellar-core/blob/a278e95978bdac6d1015d82f4859dad780e752d3/src/ledger/LedgerManagerImpl.cpp#L70

`const uint32_t LedgerManager::GENESIS_LEDGER_BASE_RESERVE = 100000000;`

The value is in stroops (1 stroop = 0.0000001 XLM ; 1 XLM = 10000000 stroops), so the current base reserve is still 10 XLM.

**Comment by beleriandcrises** [comment]
Well, @imsys, the wallet is behind anyhow, since it has the minimum to 10 XLM. Are they maybe waiting for the minimum to officially drop to 0.5 XLM to implement it?

**Comment by kfiresmith** [comment]
Polling a recent ledger, the base_reserve is in fact 0.5:  https://horizon.stellar.org/ledgers/15980333
`  "base_reserve": "0.5000000",`

...But judging from all of the unacknowledged bugs and PRs, don't get your hopes up.  

Perhaps check out Stargazer wallet - the dev is responsive and is pushing 1.5.4 right now which dynamically adjusts the base_reserve based on what the Stellar Network lists in current ledgers.

**Comment by vogel** [comment]
@imsys it is base reserve for geneis ledger (ledger number 1). It will always stays the same. For later ledgers, nodes vote for base reserve (and it has nothing to do with that constant).

**Comment by imsys** [comment]
@vogel Thanks for the correction and explanation. :)
