### ISSUE TITLE
Desktop Client Freezes

### ISSUE THREAD

**Issue by naifamoodi** [stellarchat/desktop-client#187]
Whenever I click on the 'Show Private Key' button, the application freezes. I have to end it from the task manager. I am not able to recover my private keys because of this.

OS: Windows 10 64 bit

**Comment by stellarchat** [comment]
the wallet file was saved already, you can open it again to check the secret key. Anyway, you will not lose your fund. I cannot re-produce the problem.

**Comment by naifamoodi** [comment]
I can't because the application freezes. There are others reporting the exact same problem. I don't know how to decrypt the wallet file either. Right now there is no way for me to retrieve the private-key.

I am using the following:

Windows 10 x64
Firefox as default browser
Windows Defender as AV

**Comment by naifamoodi** [comment]
This has been fixed in the latest release i.e. v3.5
