### ISSUE TITLE
Are Inflation payments being marked as 'Sent' not Received?

### ISSUE THREAD

**Issue by stevejalim** [stellarchat/desktop-client#191]
Couple of odd things here:

1) Why is this Inflation payment marked as 'Sent' not 'Received'?
![screen shot 2018-01-23 at 09 40 05](https://user-images.githubusercontent.com/101457/35268747-e1837c18-0021-11e8-9a82-d0beb4075343.png)

Transaction is: https://stellar.expert/explorer/account/GAJ2SHOU6XZK5D33OMBWMDCXMK3MT2JKJV2VWLKBCBWXWHLBVW6W2L7H 

2) Why is the inflation payment marked as 2.3335169 XLM while the Transaction above shows 4.2276393 XLM with a memo-text from the inflation pool?
![screen shot 2018-01-23 at 09 40 13](https://user-images.githubusercontent.com/101457/35268748-e198e6f2-0021-11e8-86ce-ef51a26a7820.png)

Is it just a display/labelling bug?

**Comment by stevejalim** [comment]
Indeed, thanks to the help of a kind Redditor, the issue appears to be that when a bulk payment is made, the client is displaying the value of the FIRST payment in a batch (but not necessarily the relevant payment)

https://www.reddit.com/r/lumenaut/comments/7sbah9/what_is_this_transaction_from_my_account/dt3x6ae/?context=3

**Comment by stellarchat** [comment]
The history page will only show the first operation if it is a batch. Need to improve in future.

**Comment by stellarchat** [comment]
this will be fixed in v3.6
