### ISSUE TITLE
XLM missing

### ISSUE THREAD

**Issue by Zappa1** [stellarchat/desktop-client#194]
To All, I did send, end December 2017, 4200 XLM to my Ledger Nano S account GDDHJZPDFCKVWN6DJJHXXSGXA55GGHPQH4FQ6SIIT7PHUMLPTZOJ2EAB
Not 1 XLM arrived, no help from the Forum only laughter.
1 week later I did send 150 XLM to a new installed Desktop client:
GAVUITLTUF4WNPW32XZAYG57Q5ME3MFZABUYVVSLOK6DRR7AEJ4MZZKZ
again nothing arrived at my wallet.
Quoine from where I did send the XLM answered that the wallet was not existing
Ledger did anwer with FAQ and Stellar did not answer at all, I did send the 3 companies pictures and explaination
How is this possible, where are my XLM????
Cheers Dirk

**Comment by kfiresmith** [comment]
From where did you send your XLM?  You posted two empty wallet addresses above, but no information about the origin of either attempted transaction, nor any transaction IDs.  

No transaction IDs, no transaction.

**Comment by Zappa1** [comment]
I did send the XLM from Quoine, as you can see on the pictures. 


Van: "Kodiak Firesmith" <notifications@github.com> 
Aan: "stellarchat/desktop-client" <desktop-client@noreply.github.com> 
Cc: "Zappa1" <revita.dirk@telenet.be>, "Author" <author@noreply.github.com> 
Verzonden: Zondag 28 januari 2018 14:45:51 
Onderwerp: Re: [stellarchat/desktop-client] XLM missing (#194) 



From where did you send your XLM? You posted two empty wallet addresses above, but no information about the origin of either attempted transaction, nor any transaction IDs. 

No transaction IDs, no transaction.

**Comment by kfiresmith** [comment]
There are no pictures in this github issue - not sure what you are talking about.

**Comment by kfiresmith** [comment]
From what I gather you sent out withdrawals from the Japanese exchange Quoine, and they never arrived though Quoine asserts that they were sent out.  

If that is the case, you should be able to retrieve transaction IDs from the exchange and look those up on the Stellar network explorer.  Posting empty wallet addresses in this thread will not help anything, we can all agree that those two addresses are empty.

**Comment by Zappa1** [comment]
Correct,
Quoine admided that the last withdrawal was not correct and retrieved the 147 XLM I did send to my new installed Desktop client:
GAVUITLTUF4WNPW32XZAYG57Q5ME3MFZABUYVVSLOK6DRR7AEJ4MZZKZ
this was a second try, I would like to have my 4200 XLM back, I recontacted Quoine for this
My concern is how in Gods name can I send the XLM I buy at Quoine to my Ledger when the wallet is not existing, somebody send me 5 XLM?

**Comment by kfiresmith** [comment]
Always send a small amount first to test.  Don't just send 4200 XLM to a wallet address that isn't proven yet.  
Go find your transaction ID for the 4200 XLM transaction and post that transaction ID.  From what I'm seeing for **multiple currency types** on the Ledger support subreddit, there are major problems with Ledger not doing transactions properly.  Until there is an actual transaction ID for the 4200 XLM transaction, you have nothing to go on.

**Comment by Zappa1** [comment]
Thanks, 
the first who answers me how to act, I will go for the Transaction ID at the Quoine platform.
I let you know how it ends.
Cheers
Dirk
Op 28-jan.-2018, om 17:10 heeft Kodiak Firesmith <notifications@github.com> het volgende geschreven:

**Comment by kfiresmith** [comment]
@Zappa1  - I understand that there is probably a language barrier issue here but I don't know what you mean with that last reply.  Just pull up the transaction ID and that will tell you if anything was actually sent out over the Stellar network, or if the XLM never actually left the exchange.  It certainly never landed in the wallet address you listed in your first post (GDDHJZPDFCKVWN6DJJHXXSGXA55GGHPQH4FQ6SIIT7PHUMLPTZOJ2EAB), so it probably did not go out onto the network.

**Comment by kfiresmith** [comment]
For example, this is a transaction as viewed on the Stellar Network Explorer:
https://stellarchain.io/tx/0e2542d8e7af067fbd6c598a6f5de46d9b182a7c6dfde793dca635e25d8e83c2

Transactions are different than wallets, and show the actual movement of XLM between two wallet/key IDs

**Comment by Zappa1** [comment]
Where can I find the Transaction ID from the 4200 XLM? At Quoine ?

Op 28-jan.-2018, om 17:23 heeft Kodiak Firesmith <notifications@github.com> het volgende geschreven:

**Comment by kfiresmith** [comment]
Yes exactly @Zappa1  - if Quoine asserts that they sent out 4200XLM, then they will have a transaction ID from the Stellar Network where that took place.  I don't use that exchange so I can't tell you how to access the right page in your trading account, but if you look around you should find the transaction ID, if an actual withdrawal from Quoine was successfully created.

By the way, from your first post: 
>  no help from the Forum only laughter.
What forum was this?  Do you have a link to the thread?

**Comment by Zappa1** [comment]
The forum on Cryptocompare, the XLM forum, believe me what you read there is not why Cryptocurrency was developed, no sense of community, they are only trying to make money.
I am there for the believe in the change and a long term hodler.

Op 28-jan.-2018, om 17:38 heeft Kodiak Firesmith <notifications@github.com> het volgende geschreven:

**Comment by kfiresmith** [comment]
Please consider joining the Stellar community at https://reddit.com/r/stellar.  It is a much more productive community, and frankly that would be the best place to get help for things like your problem.

**Comment by Zappa1** [comment]
Thanks for guiding me there, I will certainly do that.
Tomorrow I go for the Transaction ID.
Good evening and thanks
Op 28-jan.-2018, om 17:45 heeft Kodiak Firesmith <notifications@github.com> het volgende geschreven:

**Comment by Zappa1** [comment]
Dear, I did check the Quoine withdrawal site, for the XLM no ID, for the send Dash & Ether I see the ID, when I push it then I can follow the way it makes.
I did send them a mail for explaination.
Cheers Dirk

Verstuurd vanaf mijn iPad

**Comment by Zappa1** [comment]
My dear friends, 

I got my 4200 XLM back, Quoine reverted the withdrawal I did december last year. 
Thanks to you all for helping me out on this issue. 
Cheers 
Dirk 


Van: "stellarchat" <notifications@github.com> 
Aan: "stellarchat" <desktop-client@noreply.github.com> 
Cc: "Zappa1" <revita.dirk@telenet.be>, "Mention" <mention@noreply.github.com> 
Verzonden: Vrijdag 9 februari 2018 15:30:09 
Onderwerp: Re: [stellarchat/desktop-client] XLM missing (#194) 



Closed [ https://github.com/stellarchat/desktop-client/issues/194 | #194 ] .
