### ISSUE TITLE
Transferred xlm from wallet to binance never recieved

### ISSUE THREAD

**Issue by Tonyfire30** [stellarchat/desktop-client#195]
Hi there,

I made a transaction from stellar desktop client to binance, with right adress however it did not came through. Now its not in my desktop wallet nor in binance. what to do? 
<img width="1440" alt="screen shot 2018-01-30 at 11 53 10" src="https://user-images.githubusercontent.com/35958234/35563392-d06d8456-05b6-11e8-91f6-0a304f523f8d.png">
<img width="1440" alt="screen shot 2018-01-30 at 11 53 14" src="https://user-images.githubusercontent.com/35958234/35563395-d23faa48-05b6-11e8-8b9e-06c268a00b9f.png">
<img width="1440" alt="screen shot 2018-01-30 at 11 53 18" src="https://user-images.githubusercontent.com/35958234/35563399-d38ed75c-05b6-11e8-8806-48a439c2b65c.png">
<img width="1440" alt="screen shot 2018-01-30 at 11 53 24" src="https://user-images.githubusercontent.com/35958234/35563403-d4aa4e46-05b6-11e8-979c-2a7e570b17a9.png">

**Comment by kfiresmith** [comment]
Hi @Tonyfire30,
Please find your transaction ID for the send-out to binance and post that.
Also post the account IDs (public keys starting with G*), for easy copy-paste rather than just screenshots, thanks.

**Comment by Tonyfire30** [comment]
This is the transaction that went from binance to the desktop wallet stellar

610f333b34e1a89e681c14a67440971a3515d3075c49ff88ccbac90b37ae10d0

https://stellarchain.io/tx/610f333b34e1a89e681c14a67440971a3515d3075c49ff88ccbac90b37ae10d0

<img width="1440" alt="screen shot 2018-01-30 at 12 44 48" src="https://user-images.githubusercontent.com/35958234/35564730-68e5179a-05bb-11e8-9b20-ae3b1cfea7d1.png">

**Comment by kfiresmith** [comment]
Good news / bad news:
The wallet worked exactly as expected and posted a transaction to the Stellar network, you can see that here:  https://stellarchain.io/tx/8c7b56dec30ec6a2322c64b3f597893b63cffc5bf5043bead1fc8331210b89b7

The bad news is that you didn't memo the transaction properly for Binance and send an un-memo'd payment payment so now Binance doesn't know to send it into your account :(

You can read about this common mistake here:  https://www.reddit.com/r/Stellar/comments/7jvrnr/forgot_to_include_memo_depositing_xlm_to_binance/
