### ISSUE TITLE
Questions about application type and packaging

### ISSUE THREAD

**Issue by kfiresmith** [stellarchat/desktop-client#203]
3.4 looks great!  Congratulation on the release.

I have a couple questions, if someone from the dev team can respond:

1. Will this permanently be written in nw.js or are there long term plans to rebuild as an Electron App?
2. Are there any plans to start releasing this as an AppImage instead of a zip file?  The end-user experience is better with AppImage when using Linux.  https://appimage.org/

Thank you very much!

**Comment by stellarchat** [comment]
1. We will continue to use nw.js. No plan of rebuild yet.
2. Good idea. We will check it and then decide which way is more suitable for us.

**Comment by kfiresmith** [comment]
Thanks very much for the reply - good to know!
