### ISSUE TITLE
how to install on my ubuntu

### ISSUE THREAD

**Issue by cybex7** [stellarchat/desktop-client#205]
i downloaded this app on my ubuntu 16.04 but i can't install it
help me

**Comment by overcat** [comment]
```
wget https://github.com/stellarchat/desktop-client/releases/download/v3.4/StellarDesktopLinux64-v3.4.zip
unzip StellarDesktopLinux64-v3.4.zip
cd StellarDesktopLinux64-v3.4
chmod +x StellarWallet
./StellarWallet
```

**Comment by polentafredda** [comment]
@overcat , i followed the command you wrote here, but it dont really get installed,i have to re-run it from cd everytime it get closed

any suggestion
thanks

**Comment by overcat** [comment]
This is a portable application, you do not need to install it, just run it
directly.

If you want to make it appear in the application menu, you have to
configure it by yourself, for Ubuntu, please check here for more details:
https://askubuntu.com/questions/281293/creating-a-desktop-file-for-a-new-application

I recommend you add an alias for the application in your .bashrc file,
then you can start the application with just one command.

polentafredda <notifications@github.com> 于 2018年2月20日周二 05:45写道：
