### ISSUE TITLE
wallet.stellar.chat doesn't make an HTTPS connection

### ISSUE THREAD

**Issue by cmvanb** [stellarchat/desktop-client#214]
Without an HTTPS connection it is possible for a MITM (man-in-the-middle) attack to inject a malicious executable in the place of Stellar Desktop Client. In order to trust the download of your software, you should offer HTTPS connection.

**Comment by overcat** [comment]
The website host on GitHub Pages, it can not enable HTTPS for custom domain. 
So I recommend registering with Cloudflare DNS so that you(@stellarchat) can set HTTPS up properly for a site on a custom domain, another great option is to use [Netlify](https://www.netlify.com/).

**Comment by stellarchat** [comment]
Great suggestion. The website is hosted by Netlify with https support now.
