### ISSUE TITLE
Add StellarGuard support?

### ISSUE THREAD

**Issue by pselden** [stellarchat/desktop-client#238]
Hi, I'm the developer of StellarGuard.me (https://stellarguard.me) and I am wondering if you'd be open to a pull request for adding support for submitting transactions to StellarGuard.

To learn more about StellarGuard, go here: https://galactictalk.org/d/1164-stellarguard-me-secure-your-lumens-with-multisig-and-two-factor-auth or https://medium.com/@stellarguard/securing-your-stellar-lumens-with-multisig-and-stellarguard-103385c671e3

Adding StellarGuard support would mean adding https://github.com/stellarguard/stellarguard-js-sdk (or just using the angular $http service to make an http call) to the project and checking whether the user has StellarGuard enabled on your account. See https://github.com/stellarguard/stellarguard-js-sdk/blob/master/examples/index.js#L31-L35 to see how easy it is!

With this, your users will the option to have extra piece of mind that their Lumens are safe and secure, and I'll add Foxlet to https://stellarguard.me/supported-wallets page as well.

I can do the implementation and submit a Pull Request, I just want to know if this is something you would be interested in merging if I do.

Thanks!

**Comment by blackiebear** [comment]
I also would love this added, opening the wallet up for multisig would make it really safe and secure, as it doesn't have 2fa!

**Comment by pselden** [comment]
I've started work on this, but please let me know ahead of time if this is something you absolutely would not merge.
