### ISSUE TITLE
Why is it recomended to use node version 4 in readme?

### ISSUE THREAD

**Issue by Ratniex** [stellarchat/desktop-client#244]
Everything seems to work with: 
* node version 8.9.4
* nwjs version 66.0.3359.117
* npm version 5.6.0

**Comment by stellarchat** [comment]
Hmm, the stellar-sdk, one of most important lib in this project recommended use node 4. 

Actually, I think you can use node 8.

**Comment by Ratniex** [comment]
There is a plan to integrate with Ledger hardware wallet and that will break node 4 compatibility. Also I did not find where it is recommended to use node 4.

Should this issue be closed?
