### ISSUE TITLE
"Yes, I saved my secret key in a safe place" button does not dismiss ~ OSX64

### ISSUE THREAD

**Issue by jbshirk** [stellarchat/desktop-client#267]
after creating a new (first) empty account:

- by default, wants to save wallet*.txt to Macintosh HD (/) [and it should not be able to, I would hope]
- first attempt to save wallet*.txt to home (~)  does not save. (second attempt does)
- after entering and verifying new password, "Yes, I saved my secret key" button does nothing and I had to quit the app and restart it.

**Comment by Akuukis** [comment]
Which version are you using? E.g. release number of downloaded release or commit hash of used source?

**Comment by Akuukis** [comment]
Ok. The 2nd and 3rd point should be fixed in upcoming 5.0, at least for my Linux it is.

I will double-check the first point.

**Comment by jbshirk** [comment]
Hope this helps. Does new version update notice happen in the app?

**Comment by liangran** [comment]
It is quite interesting that the problem do not appear when I built the app on my Mac. It seems the problem is not caused by the code but with the CI built tool. So it cannot be fixed easily.

**Comment by liangran** [comment]
You have to close the app and restart it after you create a new wallet currently.

**Comment by stellarchat** [comment]
It is the issue when angular js upgrade 1.6 to 1.7.
