### ISSUE TITLE
lots of 404's in app

### ISSUE THREAD

**Issue by jbshirk** [stellarchat/desktop-client#268]
![screen shot 2018-07-06 at 7 11 12 pm](https://user-images.githubusercontent.com/3949396/42403673-d6d1a456-8150-11e8-9a1c-5b1691e14557.png)
![screen shot 2018-07-06 at 7 10 57 pm](https://user-images.githubusercontent.com/3949396/42403674-d6e8eac6-8150-11e8-8850-432d24f2064f.png)
![screen shot 2018-07-06 at 7 12 48 pm](https://user-images.githubusercontent.com/3949396/42403676-da57e7d4-8150-11e8-8981-d2aa34a77f2a.png)
![screen shot 2018-07-06 at 7 12 22 pm](https://user-images.githubusercontent.com/3949396/42403677-da7e4a1e-8150-11e8-8748-6670ea96bba5.png)

**Comment by Akuukis** [comment]
Is your account created? Such error shows all over the place if your account is created.

In our plans is to address it with better home view that basically says "Please fund this account to create it", and meanwhile deactivate most of tabs. Sounds good?

**Comment by Akuukis** [comment]
That's weird. Is it created on the same network as you are logged in, e.g. both are "Stellar Test Networks"? 

Otherwise please send you address, perhaps your account is a special case for some reason.

**Comment by jbshirk** [comment]
Selected Stellar Network
Passphrase: Public Global Stellar Network ; September 2015
Coin: XLM
Horizon: https://horizon.stellar.org

GDBZEJG3BDXM3OJ3QYHCZM4T4DGNRQKNL34Q64H3PRAJXEHWN5BIDRUP

**Comment by stellarchat** [comment]
@jbshirk 1, GDBZEJG3BDXM3OJ3QYHCZM4T4DGNRQKNL34Q64H3PRAJXEHWN5BIDRUP does not activated. That is why it show 404 in your wallet.

2, Do you use a old version of wallet? The error message is more friendly in later version.

**Comment by jbshirk** [comment]
The version offered at download page 3 days ago was 4.1
https://github.com/stellarchat/desktop-client/issues/267#issuecomment-403325542

Somehow during setup I missed advice to activate. I don't understand that process.

**Comment by Akuukis** [comment]
The next version of Foxlet is not released yet. A more thoughtful process is in the makings now. Today FIC Network will release a test built, as they also use this wallet for their network.

You have created an address during registration process, but not an account on blockchain yet. For account to start to exist, it has to be "activated" by sending small deposit.
