### ISSUE TITLE
blank I18t?

### ISSUE THREAD

**Issue by jbshirk** [stellarchat/desktop-client#269]
![stellar shot 2018-07-06 at 7 11 49 pm](https://user-images.githubusercontent.com/3949396/42403715-1b0d3fc2-8151-11e8-94c0-4da00356ebc4.png)

**Comment by jbshirk** [comment]
I'm assuming _s_ is meant to stand for some word, in plural.

**Comment by Akuukis** [comment]
Good catch, I will look into it.
