### ISSUE TITLE
Entering Inflation destination generates 404

### ISSUE THREAD

**Issue by jbshirk** [stellarchat/desktop-client#271]
![screen shot 2018-07-06 at 7 24 16 pm](https://user-images.githubusercontent.com/3949396/42403851-56793c0e-8152-11e8-9ada-f5f7d928abca.png)

**Comment by Akuukis** [comment]
Is your account created? Such error shows all over the place if your account is created.

In our plans is to address it with better home view that basically says "Please fund this account to create it", and meanwhile deactivate most of tabs. Sounds good?
