### ISSUE TITLE
Bug on Stellar Desktop Client ? (OSX 10.13.3)

### ISSUE THREAD

**Issue by IrvingBlanchard** [stellarchat/desktop-client#273]
Hey, I have a small bug when installing StellarWallet on Mac High Sierra 10.13.3. After writing my password and secret key, it is impossible to click on "Yes, i saved my secret key". The button is not active ... Has anyone ever had the problem ? 

Danke !

**Comment by Akuukis** [comment]
Which version of Foxlet are you using? You can get latest [v4.1](https://github.com/stellarchat/desktop-client/releases), and [v5.0.0-alpha.d4c43](https://s3.amazonaws.com/ficnetwork-public/foxlet-5.0.0-alpha.d4c43.exe) at those links.

**Comment by Akuukis** [comment]
Which version of Foxlet are you using? You can get latest [v4.1](https://github.com/stellarchat/desktop-client/releases), and [v5.0.0-alpha.d4c43](https://s3.amazonaws.com/ficnetwork-public/foxlet-5.0.0-alpha.d4c43.exe) at those links.

**Comment by IrvingBlanchard** [comment]
Thanks, I try the v4.1 but same issue. 
Download the v5.0.0 but it's an .exe file.

**Comment by Akuukis** [comment]
Oh sorry, here are all  `v5.0.0-alpha.d4c43` links for [Windows exe](https://s3.amazonaws.com/ficnetwork-public/foxlet-5.0.0-alpha.d4c43.exe), [Linux's deb](https://s3.amazonaws.com/ficnetwork-public/foxlet-5.0.0-alpha.d4c43.deb) and [Mac's zip](https://s3.amazonaws.com/ficnetwork-public/foxlet-5.0.0-alpha.d4c43.zip).

**Comment by IrvingBlanchard** [comment]
Yesss, it works ! It looks like I downloaded the wrong version the first time.
Thanks a lot Akuukis !!

**Comment by Akuukis** [comment]
Your welcome! The alpha release comes from my [fork](https://github.com/ficnetwork/foxlet/tree/blob2) which PRs (#265, and one more in-line) are not yet fully merged into upstream, so let's keep the issue open until they get merged.
