### ISSUE TITLE
I send coins, and they didnt come

### ISSUE THREAD

**Issue by M3phX** [stellarchat/desktop-client#276]
I send 599 Stellar to my binance account yesterday, and im still waiting for it, can you please hep me with this problem? Thank You

**Comment by M3phX** [comment]
Can someone help me please? i send my XLM to binance from Foxlet wallet and i still dont have it ...

**Comment by stellarchat** [comment]
Please check whether you send with a memo. If your infomation is correct, you should contact binance to credit you fund
