### ISSUE TITLE
Destination account is not created if it doesn't exist when sending

### ISSUE THREAD

**Issue by lionelve** [stellarchat/desktop-client#277]
If you try to send lumens to an unfunded account an error is returned "Request failed with status code 404". 

Instead foxlet should detect that destination account doesn't exist and create it. There is code to try and do that [here ](https://github.com/stellarchat/desktop-client/blob/16f5071346d1d96796d9107d672a1cad86f3bb7f/src/js/factory/stellar.js#L47) but it's not correctly catching the error. 

This is reproducible in the test net.

**Comment by b2397** [comment]
Good eye  @lionelve

My understanding is the `_isFunded` function [throws the error](https://github.com/stellarchat/desktop-client/blob/16f5071346d1d96796d9107d672a1cad86f3bb7f/src/js/factory/stellar.js#L53) every time, which prevents the `_send` function from handling this scenario and [funding the account](https://github.com/stellarchat/desktop-client/blob/16f5071346d1d96796d9107d672a1cad86f3bb7f/src/js/factory/stellar.js#L207).

**Comment by lionelve** [comment]
Yeah _isFunded always throws an error because the error message doesn't match in the line above.
