### ISSUE TITLE
Does the Foxlet wallet accept transactions from exchange CEX.IO?

### ISSUE THREAD

**Issue by taxedserf** [stellarchat/desktop-client#285]
Fiat-to-crypto exchange [CEX.IO](https://cex.io/) fails to transfer XLM from its wallet to the end-user's wallet (the customer's wallet), run by Foxlet Stellar Wallet.

The error happens at the last stage of the withdrawal instruction from user to CEX.IO.  The last stage is to ask for a Google Authenticator two-factor code to re-confirm the user's identity.  Immediately upon typing the 6th digit of the Google Authenticator two-factor code, CEX.IO reports an error "system not available - please try later".  The user cannot complete the withdrawal transaction.

In a support call to CEX.IO, CEX.IO said:

> As we can see, there is no funds on the wallet. So, no transactions were performed before.
> 
> Please, ask if you can send funds from crypto exchange platforms.
> If possible, you can ask about operations with CEX.IO

The transfer in question is the first transaction paid into the end-user's wallet.  Of course there's no funds in the wallet yet...!

Would a developer of Foxlet Stellar Wallet like to guess what CEX.IO is really asking, and provide a useful answer?

**Comment by stellarchat** [comment]
It is the CEX problem. They did not check whether the wallet was funded (activated). The payment type should be different (createAccount vs payment). 
1, ask CEX to update the system, check whether the account activated.
2, withdraw your XLM to a wallet already activated. (at least have 1 XLM in balance)
