### ISSUE TITLE
Issues in "master" branch

### ISSUE THREAD

**Issue by majidnk01** [stellarchat/desktop-client#299]
Hi,
I wanted to inform you that all the commits **after** **ae72f2d** Merge pull request #265 from ficnetwork/ficnetwork by stellarchat on 7/15/18 at 6:13 PM, are showing errors:
1. on switching network to user defined upon save.
**`[$rootScope:inprog] 
http://errors.angularjs.org/1.7.2/$rootScope/inprog?p0=%24apply`**

but it gets saved on restarting foxlet

2. on creating new account by secret key:
**`Request<Keystore.create/5229> failed: No valid network provided.`**

but I can confirm app works fine on open account with account file and even with user defined url.

may you review these and let me know of any possible fixes.

also I would like to contribute to this project. I can fully put time for that.

Regards

**Comment by stellarchat** [comment]
You are welcome to contribute to this wallet.

**Comment by majidnk01** [comment]
@stellarchat @ult-randolf
I can confirm the above bug is not related to create a new account page but "Network Setting" and it can be fixed by changing the **line 92 in factory.js** from **undefined** to some string as below:
`        networkPassphrase: 'Test',
`
Hope this is useful for you
And please let me know how to contribute? I can fully dedicate to this project :)
Regards
