### ISSUE TITLE
how do I find the TxID for a withdrawal

### ISSUE THREAD

**Issue by jerry-pope** [stellarchat/desktop-client#320]
I'm very new to using my Stellar wallet. 

Yesterday, exactly 24 hr ago, I sent a small amount of XLM to my Binance XLM account. I included the string "Transfer to Binance" as the Memo-text. I included a memo string because Binance requires a "memo".

As of now, 24 hr later, it still hasn't arrived at Binance. To open an issue with Binance, I need to first look into the blockchain for my withdrawal. But to do that, I need to know the transaction ID.

How do I find out what the TxID is for that withdrawal?

I looked under the Payments tab and the Transaction tab. Neither tab shows the TxID. All I see is Account ID, Amount, and Operation. The code under Operation is "107140858301665281". I'm not sure what that is.

Jerry

**Comment by Akuukis** [comment]
It's easier to find it in horizon, here, look for transactions of your account: https://www.stellar.org/laboratory/#explorer?resource=transactions&endpoint=for_account&network=public

As far I can guess, the transaction you are looking for should be the last one. To see more details, copy `envelope_xdr` to XDR Viewer.

**Comment by jerry-pope** [comment]
Thank you sir!
