### ISSUE TITLE
The BTC/XLM prices display as all 0

### ISSUE THREAD

**Issue by jedmccaleb** [stellarchat/desktop-client#44]
![rogue prices](https://cloud.githubusercontent.com/assets/399067/25095083/ed737092-234e-11e7-97d2-de64a34264cd.png)

It shows the right prices when I first look and it will show correctly if I select a different pair and then change back to BTC/XLM

**Comment by jedmccaleb** [comment]
to reproduce:  select XLM/BTC  then flip to see your balances. Then flip back to the trade tab.

**Comment by stellarchat** [comment]
https://github.com/stellarchat/desktop-client/commit/8b7ca3844ca7c42ccd51e236ae3d2653a5f72dd8

Fixed. We also release another version 1.1.0.
