### ISSUE TITLE
撤单功能有问题

### ISSUE THREAD

**Issue by fuyaocn** [stellarchat/desktop-client#72]
Stellar官方现在提供的挂单操作不会锁定账户余额，当挂单后，将账户资产转出后，本身此挂单的资产已经不够了（此问题已经提交StellarCore的Issue）此时用钱包撤销挂单时撤销不了，使用Laboratory可以撤销。

**Comment by stellarchat** [comment]
有道理。看来是用实际的price导致的问题。原来使用的是dummy, 价格是1
