### ISSUE TITLE
horizon not_found error.

### ISSUE THREAD

**Issue by daimajia** [stellarchat/desktop-client#93]
![image](https://user-images.githubusercontent.com/2503423/28809238-c9eb7b24-76b4-11e7-8c8b-7b1ffcc0c947.png)

**Comment by stellarchat** [comment]
@daimajia Make sure your account was funded by at least 20 XLM.

**Comment by jedmccaleb** [comment]
Ideally the client would tell the user this rather than this weird horizon response

**Comment by daimajia** [comment]
@jedmccaleb Holy... Hey Jed. 😲
