### ISSUE TITLE
Cant run stellar wallet antergos

### ISSUE THREAD

**Issue by ferminako** [stellarchat/desktop-client#97]
./StellarWallet
[10620:10620:0807/192448.049673:ERROR:gconf_listener.cc(117)] Error with gconf key '/apps/metacity/general': Client failed to connect to the D-BUS daemon:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Gkr-Message: couldn't connect to dbus session bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**Comment by ferminako** [comment]
nothing?????

**Comment by liangran** [comment]
I did not test on antergos. You can build it yourself.
